config/routes.rb
Rails.application.routes.draw do
  resources :users, except: %i[index new create destroy]
  resources :businesses, except: %i[index show destroy]
  resources :items

  get    '/signup', to: 'users#new'
  post   '/signup', to: 'users#create'

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root 'home#index'
end

app/models/business.rb
class Business < ActiveRecord::Base
  belongs_to :user

  has_many :items

  validates :name, :address, :city, presence: true
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :business

  validates :description, :price, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_one :business

  validates :first_name, :last_name, :email,  presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper

  # make this methods accessible in view
  helper_method :current_user, :current_business

  # authenticate user for all controllers and all actions
  # unless specified otherwise in each controller
  before_action :authenticate_user

  # authenticate user function, redirect to login page if not logged in
  def authenticate_user
    redirect_to login_path, notice: "Please login first" if current_user.blank?
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: %i[edit update]

  def new
    @business = Business.new
  end

  def create
    @business = Business.new(business_params)
    @business.user = current_user

    if @business.save
      redirect_to @business.user, notice: 'Successfully registered your business!'
    else
      flash.now[:alert] = 'Something went wrong, check the information given.'
      render :new
    end
  end

  def edit; end

  def update
    if @business.update(business_params)
      redirect_to @business.user, notice: 'Successfully updated your business!'
    else
      flash.now[:alert] = 'Something went wrong, check the information given.'
      render :edit
    end
  end

  private

  def set_business
    @business = Business.find(params[:id])
  end

  def business_params
    params.require(:business).permit(:name, :address, :city)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user.present?
      redirect_to current_user
    else
      redirect_to login_path
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[edit update destroy]

  def index
    # List all of the Items that are owned by the logged in User's Business
    if current_business.present?
      @items = current_business.items
    else
      # If business not yet created, redirect to create a new business
      redirect_to new_business_path, notice: "Please create a business."
    end
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.business = current_business

    if @item.save
      redirect_to items_path, notice: 'New item successfully added!'
    else
      flash.now[:alert] = 'Something went wrong, check the information given.'
      render :new
    end
  end

  def edit; end

  def update
    if @item.update(item_params)
      redirect_to items_path, notice: 'Item successfully updated!'
    else
      flash.now[:alert] = 'Something went wrong, check the information given.'
      render :edit
    end
  end

  def destroy
    if @item.destroy
      redirect_to items_path, notice: 'Item successfully deleted!'
    else
      flash.now[:alert] = 'Something went wrong.'
      render :index
    end
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:description, :price)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # skip authentication for methods
  skip_before_action :authenticate_user, :only => [:new, :create]

  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:alert] = 'Invalid email/password combination'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user, only: %i[new create]

  before_action :set_user, only: %i[show edit update]

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to login_path, notice: 'Successfully created user. You can now login!'
    else
      flash.now[:alert] = 'Something went wrong, check the information given.'
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Successfully updated user!'
    else
      flash.now[:alert] = 'Something went wrong, check the information given.'
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :first_name, :last_name, :email, :password, :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_for(model, *attributes)
    return if model.nil?

    mensagem = []
    attributes.each do |attr|
      model.errors[attr].each { |error| mensagem << error if mensagem.exclude?(error) }
    end

    content_tag :span, class: 'error_explanation' do
      mensagem.join(', ')
    end
  end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    current_user.nil?
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns the current Business logged-in user (if any).
  def current_business
    if current_user.present?
      @current_business ||= current_user.business
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/businesses/_form.html.erb
<%= form_with model: @business do |f| %>
  <div class="form-group">
    <%= f.label :name, 'Name*' %>
    <%= f.text_field :name, class: 'form-control' %>
    <%= error_for(@business, :name) %>
  </div>

  <div class="form-group">
    <%= f.label :address, 'Address*' %>
    <%= f.text_field :address, class: 'form-control' %>
    <%= error_for(@business, :address) %>
  </div>

  <div class="form-group">
    <%= f.label :city, 'City*' %>
    <%= f.text_field :city, class: 'form-control' %>
    <%= error_for(@business, :city) %>
  </div>

  <% if @business.new_record? %>
    <%= f.submit "Register", class: "btn btn-primary", id: "register-business-button" %>
  <% else %>
    <%= f.submit "Update", class: "btn btn-primary" %>
  <% end %>
<% end %>

app/views/businesses/edit.html.erb
<h1 class="text-center">Edit your Business info</h1>

<div class="row" id="login-container">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/businesses/new.html.erb
<h1 class="text-center">Register your Business</h1>

<div class="row" id="login-container">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/items/_form.html.erb
<%= form_with model: @item do |f| %>
  <div class="form-group">
    <%= f.label :description, 'Description*' %>
    <%= f.text_field :description, class: 'form-control' %>
    <%= error_for(@item, :description) %>
  </div>

  <div class="form-group">
    <%= f.label :price, 'Price*' %>
    <%= f.number_field :price, class: 'form-control' %>
    <%= error_for(@item, :price) %>
  </div>

  <%= f.submit "Add", class: "btn btn-primary" %>
<% end %>

app/views/items/edit.html.erb
<h1 class="text-center">Edit Item</h1>

<div class="row" id="login-container">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/items/index.html.erb
<% provide(:title, "Items") %>

<h1>Listing items</h1>

<th><%= link_to "Add a new Item", new_item_path, class: "btn btn-primary" %></th><br><br>

<% if @items.empty? %>
  <p>Your Business currently has no Items.</p>
<% else %>
  <table class="table table-hover item-list">
    <tr>
      <th>#</th>
      <th>DESCRIPTION</th>
      <th>PRICE</th>
      <th>OPTIONS</th>
    </tr>

    <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= item.description %></td>
        <td><%= item.price %></td>
        <td>
          <%= link_to "Edit", edit_item_path(item), class: "btn btn-default" %>
          <%= link_to "Delete", item_path(item), method: :delete, class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/items/new.html.erb
<h1 class="text-center">Add new Item</h1>

<div class="row" id="login-container">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <a href="/"><h2 class="header-main">Taki Rails Interview</h1></a>
  <nav>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <ul>
          <% if current_business.blank? %>
            <li><%= link_to "Create Business", new_business_path %></li>
          <% else %>
            <li><%= link_to "Edit Business", edit_business_path(current_user.business) %></li>
            <li><%= link_to "Business Items", items_path %></li>
          <% end %>

          <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
          <li class="divider"></li>
          <li>
            <%= link_to "Log out", logout_path, method: "delete" %>
          </li>
        </ul>
      <% else %>
        <li><%= link_to "Log in", login_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taki Rails Interview</title>

    <!-- Bootstrap 4.0 imports -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

  <%= render 'layouts/header' %>

  <div class="container">
    <!-- flash message -->
    <% if notice.present? %>
      <p id="notice"><%= notice %></p>
    <% end %>

    <% if alert.present? %>
      <p id="alert"><%= alert %></p>
    <% end %>


    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>

  </body>
</html>

app/views/users/_form.html.erb
  <div class="col-md-6 col-md-offset-3" id="signup-form">
    <%= form_with model: @user do |f| %>
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: "form-control" %>
      <%= error_for(@user, :first_name) %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: "form-control" %>
      <%= error_for(@user, :last_name) %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
      <%= error_for(@user, :email) %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
      <%= error_for(@user, :password) %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
      <%= error_for(@user, :password_confirmation) %>

      <% if @user.new_record? %>
        <%= f.submit "Create my account", class: "btn btn-primary" %>
      <% else %>
        <%= f.submit "Edit information", class: "btn btn-primary" %>
      <% end %>
    <% end %>
  </div>

app/views/users/edit.html.erb
<% provide(:title, 'Profile info') %>
<h1 class="text-center">Profile info</h1>
<div class="row">
  <%= render 'form' %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1 class="text-center">Sign up</h1>
<div class="row">
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<% provide(:title, 'Profile info') %>
<div class="card" style="width: 50%; margin: auto;">
  <h1 class="text-center">Profile info</h1>
  <div class="card-body d-flex flex-column justify-content-center">
    <div class="offset-md-3">
      <p>
        <span><strong>Name: </strong></span>
        <%= "#{@user.first_name} #{@user.last_name}" %>
      </p>
    </div>

    <div class="offset-md-3">
      <p>
        <span><strong>Email: </strong></span>
        <%= @user.email %>
      </p>
    </div>

    <% if current_business.present? %>
      <div class="offset-md-3">
        <p>
          <span><strong>Business Name: </strong></span>
          <%= @user.business.name %>
        </p>
      </div>

      <div class="offset-md-3">
        <p>
          <span><strong>Business Address: </strong></span>
          <%= @user.business.address %>
        </p>
      </div>

      <div class="offset-md-3">
        <p>
          <span><strong>Business City: </strong></span>
          <%= @user.business.city %>
        </p>
      </div>
    <% end %>
  </div>
</div>